// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TireForge.Data;

#nullable disable

namespace TireForge.Data.Migrations
{
    [DbContext(typeof(TireForgeDbContext))]
    [Migration("20260902210720_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TireForge.Core.Model.Diagnosis", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnoseText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fault")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("GateReason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentCites")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadingId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReadingId");

                    b.HasIndex("Status");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("TireForge.Core.Model.HistoryIncident", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fault")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "Signature");

                    b.ToTable("History");
                });

            modelBuilder.Entity("TireForge.Core.Model.Machine", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastMaintenance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeedStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("TireForge.Core.Model.Reading", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<long>("CapturedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsAnomaly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<double>("Pressure")
                        .HasColumnType("REAL");

                    b.Property<double>("Rpm")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<double>("Vibration")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "CapturedAt");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("TireForge.Core.Model.WorkOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosisId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fault")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReadingId")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectNote")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("TireForge.Core.Model.Diagnosis", b =>
                {
                    b.HasOne("TireForge.Core.Model.Reading", "Reading")
                        .WithMany()
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");
                });

            modelBuilder.Entity("TireForge.Core.Model.HistoryIncident", b =>
                {
                    b.HasOne("TireForge.Core.Model.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("TireForge.Core.Model.Machine", b =>
                {
                    b.OwnsOne("TireForge.Core.Model.SensorBand", "Pressure", b1 =>
                        {
                            b1.Property<string>("MachineId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Max")
                                .HasColumnType("REAL");

                            b1.Property<double>("Min")
                                .HasColumnType("REAL");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.OwnsOne("TireForge.Core.Model.SensorBand", "Rpm", b1 =>
                        {
                            b1.Property<string>("MachineId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Max")
                                .HasColumnType("REAL");

                            b1.Property<double>("Min")
                                .HasColumnType("REAL");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.OwnsOne("TireForge.Core.Model.SensorBand", "Temperature", b1 =>
                        {
                            b1.Property<string>("MachineId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Max")
                                .HasColumnType("REAL");

                            b1.Property<double>("Min")
                                .HasColumnType("REAL");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.OwnsOne("TireForge.Core.Model.SensorBand", "Vibration", b1 =>
                        {
                            b1.Property<string>("MachineId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Max")
                                .HasColumnType("REAL");

                            b1.Property<double>("Min")
                                .HasColumnType("REAL");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("MachineId");

                            b1.ToTable("Machines");

                            b1.WithOwner()
                                .HasForeignKey("MachineId");
                        });

                    b.Navigation("Pressure")
                        .IsRequired();

                    b.Navigation("Rpm")
                        .IsRequired();

                    b.Navigation("Temperature")
                        .IsRequired();

                    b.Navigation("Vibration")
                        .IsRequired();
                });

            modelBuilder.Entity("TireForge.Core.Model.Reading", b =>
                {
                    b.HasOne("TireForge.Core.Model.Machine", "Machine")
                        .WithMany("Readings")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("TireForge.Core.Model.WorkOrder", b =>
                {
                    b.HasOne("TireForge.Core.Model.Diagnosis", "Diagnosis")
                        .WithOne("WorkOrder")
                        .HasForeignKey("TireForge.Core.Model.WorkOrder", "DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("TireForge.Core.Model.Diagnosis", b =>
                {
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("TireForge.Core.Model.Machine", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
