#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# TireForge — regenerate factory/.env from the already-deployed Challenge 0
# resources. Safe to commit: contains no secrets, only resource names. Secrets
# (App Insights connection string / key) are pulled from Azure at run time.
#
# Use this after a Codespace rebuild instead of re-running deploy.sh (which
# would provision a *new* resource group with a new suffix).
#
# Requires: az login  (subscription DkaySubscription)
# Usage:    bash tireforge/scripts/restore-env.sh
# =============================================================================

SUBSCRIPTION_ID="b5e77c80-223c-4cba-992e-c703545854b4"
RESOURCE_GROUP="foundry-hackathon-rg-3e97ae19"
FOUNDRY_RESOURCE_NAME="foundry-hack-3e97ae19"
PROJECT_NAME="factory-project"
MODEL_DEPLOYMENT_NAME="gpt-5.4"
APP_INSIGHTS_NAME="foundry-hack-insights-3e97ae19"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$REPO_ROOT/factory/.env"

echo ">>> Using subscription $SUBSCRIPTION_ID"
az account set --subscription "$SUBSCRIPTION_ID"

echo ">>> Checking resource group $RESOURCE_GROUP ..."
if ! az group show --name "$RESOURCE_GROUP" --output none 2>/dev/null; then
  echo "❌ Resource group '$RESOURCE_GROUP' not found."
  echo "   The Challenge 0 resources were deleted. Re-run: bash factory/challenge-0-setup/deploy.sh"
  exit 1
fi

echo ">>> Retrieving endpoints and keys ..."
FOUNDRY_ENDPOINT=$(az cognitiveservices account show \
  --name "$FOUNDRY_RESOURCE_NAME" --resource-group "$RESOURCE_GROUP" \
  --query "properties.endpoint" -o tsv)

PROJECT_CONNECTION_STRING=$(az cognitiveservices account project show \
  --name "$FOUNDRY_RESOURCE_NAME" --resource-group "$RESOURCE_GROUP" \
  --project-name "$PROJECT_NAME" \
  --query "properties.endpoints.\"AI Foundry API\"" -o tsv)

APP_INSIGHTS_CONN_STRING=$(az monitor app-insights component show \
  --app "$APP_INSIGHTS_NAME" --resource-group "$RESOURCE_GROUP" \
  --query connectionString -o tsv)

APP_INSIGHTS_INSTRUMENTATION_KEY=$(az monitor app-insights component show \
  --app "$APP_INSIGHTS_NAME" --resource-group "$RESOURCE_GROUP" \
  --query instrumentationKey -o tsv)

echo ">>> Writing $ENV_FILE"
cat > "$ENV_FILE" << EOF
# =============================================================================
# Foundry Hackathon — Environment Variables
# Regenerated by tireforge/scripts/restore-env.sh on $(date)
# =============================================================================

# Azure Subscription
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
RESOURCE_GROUP=$RESOURCE_GROUP

# AI Foundry
FOUNDRY_RESOURCE_NAME=$FOUNDRY_RESOURCE_NAME
PROJECT_NAME=$PROJECT_NAME
FOUNDRY_ENDPOINT=$FOUNDRY_ENDPOINT
PROJECT_CONNECTION_STRING=$PROJECT_CONNECTION_STRING
MODEL_DEPLOYMENT_NAME=$MODEL_DEPLOYMENT_NAME

# Application Insights & Monitoring
APPLICATIONINSIGHTS_CONNECTION_STRING=$APP_INSIGHTS_CONN_STRING
APPINSIGHTS_INSTRUMENTATION_KEY=$APP_INSIGHTS_INSTRUMENTATION_KEY

# Tracing (set to true to enable GenAI tracing)
AZURE_EXPERIMENTAL_ENABLE_GENAI_TRACING=true
OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=true
EOF

echo ""
echo "✅ factory/.env restored."
